export const GET_HOLDIGS_BEGINS = "GET_HOLDIGS_BEGINS";
export const GET_HOLDIGS_SUCCESS = "GET_HOLDIGS_SUCCESS";
export const GET_HOLDIGS_FAILURE = "GET_HOLDIGS_FAILURE";

export const GET_MARKET_BEGINS = "GET_MARKET_BEGINS";
export const GET_MARKET_SUCCESS = "GET_MARKET_SUCCESS";
export const GET_MARKET_FAILURE = "GET_MARKET_FAILURE";
